
#include <stdlib.h>
#include <string.h>

#include <stdio.h>


// include NESLIB header
#include "neslib.h"

// include CC65 NES Header (PPU)
#include <nes.h>

// link the pattern table into CHR ROM
//#link "chr_generic.s"

///// METASPRITES

// define a 2x2 metasprite
#define DEF_METASPRITE_2x2(name,code,pal)\
const unsigned char name[]={\
        0,      0,      (code)+0,   pal, \
        0,      8,      (code)+1,   pal, \
        8,      0,      (code)+2,   pal, \
        8,      8,      (code)+3,   pal, \
        128};

// define a 2x2 metasprite, flipped horizontally
#define DEF_METASPRITE_2x2_FLIP(name,code,pal)\
const unsigned char name[]={\
        8,      0,      (code)+0,   (pal)|OAM_FLIP_H, \
        8,      8,      (code)+1,   (pal)|OAM_FLIP_H, \
        0,      0,      (code)+2,   (pal)|OAM_FLIP_H, \
        0,      8,      (code)+3,   (pal)|OAM_FLIP_H, \
        128};

// BCD arithmetic support
#include "bcd.h"
//#link "bcd.c"

// VRAM update buffer
#include "vrambuf.h"
//#link "vrambuf.c"

// number of rows in scrolling playfield (without status bar)
#define PLAYROWS 30
#define PLAYCOLUMNS 32
// RNG, from BluBlue On bayoen discord
/*dans le vrai Tsu, le jeu prend 256 puyos répartis équitablement avec les 4 couleurs de la partie, donc 64 de chaque
il les mélange en les échangeant de place
la liste qui en résulte est la suite de paires qu'on aura : les deux premiers forment la première paire, etc*/
// He has also completely deconstruct the RNG of puyo there: https://puyonexus.com/wiki/Puyo_Puyo_Tsu/Random_Number_Generator
// For my own sanity I will build my own RNG based on the principal of 4*64 colors being used 
#define NBCOLORPOOL 64
//256 puyos = 128 pairs...
//an attribute table entry is 2 bits, so 1 puyo = 2bits
//a pair of puyo = 4 bits
//with 8 bits we have 2 pairs
//So we need an array length of 64 bytes/char to stock everything, amazing !
#define PUYOLISTLENGTH 64

/// GLOBAL VARIABLES
//note on CellType: PUYO_RED is first and not EMPTY for 0, because it's matching the attribute table
//(I think I will regret that decision later...)
typedef enum CellType {PUYO_RED, PUYO_BLUE, PUYO_GREEN, PUYO_YELLOW, OJAMA, EMPTY, PUYO_POP};
typedef enum Step {PLAY, CHECK, CHECK_ALL, DESTROY, FALL, POINT};
word x_scroll;		// X scroll amount in pixels
byte seg_height;	// segment height in metatiles
byte seg_width;		// segment width in metatiles
byte seg_char;		// character to draw
byte seg_palette;	// attribute table value
byte step_p1, step_p2;
byte step_p1_counter, step_p2_counter;// indicates where we are in the process.
// attribute table in PRG ROM
byte attribute_table[64];/* = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // rows 0-3
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // rows 4-7
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // rows 8-11
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // rows 12-15
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // rows 16-19
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // rows 20-23
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // rows 24-27
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00  // rows 28-29
};*/
//both play tables can be stored in a 6*13 array of byte
//4 LSB are for board one, value car by of type CellType (1 bit unused), so must use &0xf to get correct value 
//4 MSB are for 2nd board, so must use >>4 to get correct value, or even better (value&240)>>4, probably overkill
//and still 1 bit unused.
//[0][0] is top left, [5][12] is bottom right, keeping same axis than display for simplification
byte boards[6][13];
//for sake of simplicity keeping the same table type for tmp
//but we may look for something less huge in size later.
byte tmp_boards[6][13];

// buffers that hold vertical slices of nametable data
char ntbuf1[PLAYROWS];	// left side
char ntbuf2[PLAYROWS];	// right side

// a vertical slice of attribute table entries
char attrbuf[PLAYROWS/4];

// nos sprites de puyo
DEF_METASPRITE_2x2(puyo_red, 0xd8, 0);//red
DEF_METASPRITE_2x2(puyo_blue, 0xd8, 1);//blue
DEF_METASPRITE_2x2(puyo_green, 0xd8, 2);//green
DEF_METASPRITE_2x2(puyo_yellow, 0xd8, 3);//yellow
DEF_METASPRITE_2x2(ojama, 0xdc, 0);
DEF_METASPRITE_2x2(puyo_pop, 0xe0, 0);

//will listed all our puyo to come, generated by RNG
char puyo_list[PUYOLISTLENGTH];
char p1_puyo_list_index;
char p2_puyo_list_index;

// number of actors (4 h/w sprites each)
// 12 : 2 active on each players screen
// and 4 for preview on each side
#define NUM_ACTORS 4

// actor x/y positions
byte actor_x[NUM_ACTORS];
byte actor_y[NUM_ACTORS];
// actor x/y deltas per frame (signed)
sbyte actor_dx[NUM_ACTORS];
sbyte actor_dy[NUM_ACTORS];

//Variables for damages 
//cf https://www.bayoen.fr/wiki/Tableau_des_dommages for how to compute damages.
byte nb_puyos_destroyed[2]; //how many puyos are destroyed on that hit
byte nb_hit[2];// hit combo counter
byte mask_color_destroyed; // LSB p1, MSB p2, bit mask at 1 for each color present in the hit. bit 0 red, bit 1 blue, bit 2 green, 3 yellow 
byte nb_group[2];//if the group is over 4 puyos add the part over in this variable.
unsigned long int score[2];
unsigned long int ojamas[4];// 2 pockets of ojama per player, but what is displayed is always the sum of both. Warikomi rule.

//INPUT BUFFER DELAY
#define INPUT_DIRECTION_DELAY 4
#define INPUT_BUTTON_DELAY 4
//previously declared in main()
char oam_id;	// sprite ID
char pad;	// controller flags
char previous_pad[2];
char input_delay_PAD_LEFT[2]; //to avoid multiple input on one press
char input_delay_PAD_RIGHT[2]; //to avoid multiple input on one press
char input_delay_PAD_A[2]; //to avoid multiple input on one press
char input_delay_PAD_B[2]; //to avoid multiple input on one press
char column_height[12]; // heigth of the stack, 0 to 5 p1, 6 to 11 P2, may not be the best strategy

//le const machin const permet de placer l'info en rom et donc de gagner de la place en théorie
const unsigned char* const puyoSeq[6] = {
  puyo_red, puyo_blue, puyo_green, puyo_yellow, ojama, puyo_pop
};

// convert from nametable address to attribute table address
word nt2attraddr(word a) {
  return (a & 0x2c00) | 0x3c0 |
    ((a >> 4) & 0x38) | ((a >> 2) & 0x07);
}

// draw metatile into nametable buffers
// y is the metatile coordinate (row * 2)
// ch is the starting tile index in the pattern table
void set_metatile(byte y, byte ch) {
  ntbuf1[y*2] = ch;
  ntbuf1[y*2+1] = ch+1;
  ntbuf2[y*2] = ch+2;
  ntbuf2[y*2+1] = ch+3;
}

void clear_metatile(byte y)
{
  ntbuf1[y*2] = 0;
  ntbuf1[y*2+1] = 0;
  ntbuf2[y*2] = 0;
  ntbuf2[y*2+1] = 0;
}

// set attribute table entry in attrbuf
// x and y are metatile coordinates
// pal is the index to set
void set_attr_entry(byte x, byte y, byte pal) {
  if (y&1) pal <<= 4;
  if (x&1) pal <<= 2;
  attrbuf[y/2] |= pal;
}

// write attribute table buffer to vram buffer
/*void put_attr_entries(word addr) {
  byte i;
  for (i=0; i<PLAYROWS/4; i++) {
    VRAMBUF_PUT(addr, attrbuf[i], 0);
    addr += 8;
  }
  vrambuf_end();
}*/

void put_attr_entries(word addr, byte length) {
  byte i;
  for (i=0; i<length; i++) {
    VRAMBUF_PUT(addr, attrbuf[i], 0);
    addr += 8;
  }
  vrambuf_end();
}

/*{pal:"nes",layout:"nes"}*/
const char PALETTE[32] = { 
  0x0D,			// screen color

  0x26,0x20,0x16,0x00,	// background palette 0
  0x39,0x20,0x11,0x00,	// background palette 1
  0x15,0x20,0x2A,0x00,	// background palette 2
  0x12,0x20,0x28,0x00,   // background palette 3

  0x23,0x20,0x16,0x00,	// sprite palette 0
  0x2C,0x20,0x11,0x00,	// sprite palette 1
  0x28,0x20,0x2A,0x00,	// sprite palette 2
  0x2D,0x20,0x28	// sprite palette 3
};

//generates the puyo that will be used during gameplay, they will be stock into puyo_list
void generate_rng()
{
  char nb_red = NBCOLORPOOL; // palette 0
  char nb_blue = NBCOLORPOOL; // palette 1
  char nb_green = NBCOLORPOOL; // palette 2 
  char nb_yellow = NBCOLORPOOL; // palette 3
  char tmp;
  byte i, j, redo;
  // puyo_list contains 64 (PUYOLISTLENGTH) char/8 bits info
  // each 8 bits contains 2 pairs as 1 puyo is a 2 bits color
  // as we have 4 colors palettes
  // the method used here is probably attrocious in term of optimization
  // but it should works.
  // we will be using rand8(), which is fast but...not very random
  rand();
  for (i = 0 ; i < PUYOLISTLENGTH ; i++)
  {
    puyo_list[i] = 0; //reinit
    redo = 1; // loop until we get what we want;
    //get a number between 0 and 3
    for (j = 0 ; j < 4; j++)
    {
      do
      {
        tmp = rand() & 3;
        switch (tmp)
        {
          case 0:
            if (nb_red > 0)
            {
              nb_red--;
              redo = 0;
              puyo_list[i] += (tmp);
            }
            break;
          case 1:
            if (nb_blue > 0)
            {
              nb_blue--;
              redo = 0;
              puyo_list[i] += (tmp << j*2);
            }
            break;
          case 2:
            if (nb_green > 0)
            {
              nb_green--;
              redo = 0;
              puyo_list[i] += (tmp << j*2);
            }
            break;
          case 3:
            if (nb_yellow > 0)
            {
              nb_yellow--;
              redo = 0;
              puyo_list[i] += (tmp << j*2);
            }
            break;
        }
      }while (redo);
    } 
  }
}

//return the color of the sprite given by the index in parameter
//OAM is a $200, each sprites uses 4 bytes, but we use metasprites of 4 bytes
//So metasprite 0 is at 200, 1 at 210,3 at 220 etc
//The attributes also contains the flip info, so mask it to 0x3 to only have color
byte return_sprite_color(byte spr_index)
{
  OAMSprite  *spr_ptr = (OAMSprite*)(0x200+16*spr_index);
  return (spr_ptr->attr & 0x3);
}

//based on sprite x/y position look for the bg attributes related to it
//find color value based on sprite index and returned the byte with the 4 tiles
//updated with sprite color
byte return_attribute_color(byte spr_index, byte spr_x, byte spr_y, byte * attr_table)
{
  //word addr = nt2attraddr(NTADR_A(spr_x,spr_y));
  byte attr_x = spr_x&0xfc;
  byte attr_y = spr_y&0xfc;
  byte attr;
  byte index;
  byte sprite_color = return_sprite_color(spr_index);
  byte mask = 3;
  //we must not override colors of the tiles around the one we change
  //We must determine were our meta sprite is located in the 4*4 metatile attributes
  //if x is odd it will be on the right, even left
  //if y is odd it will be on the bottom, even top
  //LSB is top left, MSB bottom right
  if (attr_y < spr_y)
  {
    mask <<= 4;
    sprite_color <<= 4;
  }
  if (attr_x < spr_x) 
  {
    mask <<= 2;
    sprite_color <<= 2;
  }
  // attribute position is y/2 + x/4 where y 2 LSB are 0
  index = (attr_y<<1) + (spr_x>>2);

  attr = attr_table[index];
  //let's erase the previous attributes for the intended position
  attr &= ~mask; //~ bitwise not, so we keep only bit outside of mask from attr
  attr += sprite_color;
  attr_table[index] = attr;
  return attr;
}

/* same as return_attribute_color but the color is in parameter, not get from sprite*/
byte return_tile_attribute_color(byte color, byte spr_x, byte spr_y)
{
 //word addr = nt2attraddr(NTADR_A(spr_x,spr_y));
  byte attr_x = spr_x&0xfc;
  byte attr_y = spr_y&0xfc;
  byte attr;
  byte index;
  byte mask = 3;
  //we must not override colors of the tiles around the one we change
  //We must determine were our meta sprite is located in the 4*4 metatile attributes
  //if x is odd it will be on the right, even left
  //if y is odd it will be on the bottom, even top
  //LSB is top left, MSB bottom right
  if (attr_y < spr_y)
  {
    mask <<= 4;
    color <<= 4;
  }
  if (attr_x < spr_x) 
  {
    mask <<= 2;
    color <<= 2;
  }
  // attribute position is y/2 + x/4 where y 2 LSB are 0
  index = (attr_y<<1) + (spr_x>>2);

  attr = attribute_table[index];
  //let's erase the previous attributes for the intended position
  attr &= ~mask; //~ bitwise not, so we keep only bit outside of mask from attr
  attr += color;
  attribute_table[index] = attr;
  return attr;
}

//Update the boards table, once the puyos have stop moveing, not  optimized :-S
//board_index must take 0 or 2
void update_boards(byte board_index)
{
  byte x,y;
  //char str[32];
  if (board_index == 0)
  { 
    //we must be careful not to erase the data for p2 table
    //column 0 is at 2 for actor_x[board_index]>>3, it gives us an offset, and we need to divide by 2 after to 
    //get the column number right
    x = ((actor_x[board_index]>>3) - 2) >> 1;
    y = ((actor_y[board_index]>>3)+1)>>1;
    //sprintf(str,"%d",(boards[x][y]&240));
    //vrambuf_put(NTADR_A(20,13),str,3);
    boards[x][y] = (boards[x][y]&240) + return_sprite_color(0);
   /* sprintf(str,"x:%d y:%d val:%d buf:%da",x , y, boards[x][y], return_sprite_color(0));
    vrambuf_put(NTADR_A(1,26),str,24);*/
    x = ((actor_x[board_index+1]>>3) - 2) >> 1;
    y = ((actor_y[board_index+1]>>3)+1)>>1;
   // sprintf(str,"%d",(boards[x][y]&240));
    //vrambuf_put(NTADR_A(20,14),str,3);
    boards[x][y] = (boards[x][y]&240) + return_sprite_color(1);
    /*sprintf(str,"x:%d y:%d val:%d buf:%da", x, y, boards[x][y], return_sprite_color(1));
    vrambuf_put(NTADR_A(1,27),str,24);*/

  }
  else
  {
    //we must be careful to not erase the ddata for p1 table
    //column 0 is at 18 for actor_x[board_index]>>3, it gives us an offset, and we need to divide by 2 after to 
    //get the column number  right
    x = ((actor_x[board_index]>>3) - 18) >> 1;
    y = ((actor_y[board_index]>>3)+1)>>1;
    boards[x][y] = (boards[x][y]&15) + (return_sprite_color(2) << 4);
    x = ((actor_x[board_index+1]>>3) - 18) >> 1;
    y = ((actor_y[board_index+1]>>3)+1)>>1;
    boards[x][y] = (boards[x][y]&15) + (return_sprite_color(3) << 4);
  }
}

// Look for puyo to destroy and flag them as such
byte check_board(byte board_index, byte x, byte y)
{
  static byte i, j, current_color; //static are faster, but they are keeping there value outside of context
  byte counter = 0, tmp_counter = 0;
  byte mask = 15, flag = 8, shift = 0;
  byte destruction = 0;
  //char str[32];
  
  if (board_index != 0)
  {
    shift = 4;
    mask <<= shift;
    flag <<= shift; //the 8th bit unused by color will serve as flag to check colors.
  }
  
  //to gain time we start from position of the last placed puyos
  //actor_x[board_index], actor_y[board_index],actor_x[board_index+1], actor_y[board_index+1],
  //x,y for each last puyo should be save somehere to gain time
  /*x = ((actor_x[board_index]>>3) - 2) >> 1;
  y = ((actor_y[board_index]>>3)+1)>>1;*/
  // First find puyo of the same color up, down, left, right to the current one.=, if no found exit
  // then move to the line above and below and check for a puyo of same color nearby
  // raise counter
  // until no more puyo left.
  // redo for next puyo
  // that way contrary to previous method we should not miss some boom.
  // Note : how to do when after destruction ?
  //k == current line above, k == current line below
  
  memset(tmp_boards,0,sizeof(tmp_boards));

  current_color = ((boards[x][y] & mask) >> shift);
  /*sprintf(str,"color:%d",current_color);
  vrambuf_put(NTADR_A(18,10),str,10);*/
  //tmp_boards contains flag of the currently looked color 
  tmp_boards[x][y] = flag;
  i = (x - 1); //byte are unsigned, so -1 = 255, we will not enter in the while if i < 0
  while ( i < 6 )
  {
    if ( tmp_boards[i][y] != flag)
    {
      if (current_color == ((boards[i][y] & mask) >> shift))
      {     
        tmp_boards[i][y] = flag;
        ++counter;
      }
      else
      {  
       /* i = 7; //no need to continue if not found
        continue;*/
        break;
      }
    }
    --i;
  }
  
  i = (x + 1);
  while ( i < 6 )
  {
    if ( tmp_boards[i][y] != flag)
    {
      if (current_color == ((boards[i][y] & mask) >> shift))
      {     
        tmp_boards[i][y] = flag;
        ++counter;
      }
      else
      {
        /*i = 7; //no need to continue if not found
        continue;*/
        break;
      }
    }
    ++i;
  }
  
  i = (y - 1);
  while ( i < 13 )
  {
    if ( tmp_boards[x][i] != flag)
    {
      if (current_color == ((boards[x][i] & mask) >> shift))
      {     
        tmp_boards[x][i] = flag;
        ++counter;
      } 
      else
      {
        //i = 14; //no need to continue if not found
        break;
      }
    }
    --i;
  }
  
  i = (y + 1);
  while ( i < 13 )
  {
    if ( tmp_boards[x][i] != flag)
    {
      if (current_color == ((boards[x][i] & mask) >> shift))
      {     
        tmp_boards[x][i] = flag;
        ++counter;
      } 
      else
      {
        //i = 14; //no need to continue if not found
        break;
      }
    }
    ++i;
  }
  //nothing found ? exit !
  if (counter == 0)
    return 0;
  
  //ok so we got something, now looking for more
  j = (y-1);
  //we go above, so we look below, left and right
  //we must do the line in both way (0 to 6 and 6 to 0) to avoid missing something
  while (j < 13)
  {
    for (i = 0; i < 6 ; ++i)
    {
      if (tmp_boards[i][j] != flag)
      {
        if ((current_color == ((boards[i][j] & mask) >> shift)))
        {
          if ((tmp_boards[i][j+1] == flag))
          {
            tmp_boards[i][j] = flag;
            ++counter;
            ++tmp_counter;
            continue;
          }
          else if (i > 0 && tmp_boards[i-1][j] == flag)
          {
            //look left
            tmp_boards[i][j] = flag;
            ++counter;
            ++tmp_counter;
            continue;
          }
          else if (i < 5 && tmp_boards[i+1][j] == flag)
          {
            //look right
            tmp_boards[i][j] = flag;
            ++counter;
            ++tmp_counter;
            continue;
          }
        }
      }
    }
    //no need to go backward if nothing has been foun in the first loop
    if (tmp_counter != 0) 
    {
      for (i = 5; i < 6 ; --i)
      {
        //no need to look below as it has already been done in the previous loop
        if (tmp_boards[i][j] != flag)
        {
          if ((current_color == ((boards[i][j] & mask) >> shift)))
          {
            if (i > 0 && tmp_boards[i-1][j] == flag)
            {
              //look left
              tmp_boards[i][j] = flag;
              ++counter;
              continue;
            }
            else if (i < 5 && tmp_boards[i+1][j] == flag)
            {
              //look right
              tmp_boards[i][j] = flag;
              ++counter;
              continue;
            }
          }
        }
      }
    }
    tmp_counter = 0;
    --j; //going above is getting lower j
  }
  
  j = y+1;
  //we go below so we look above
  while (j < 13)
  {
    for (i = 0; i < 6 ; ++i)
    {
      if (tmp_boards[i][j] != flag)
      {
        if ((current_color == ((boards[i][j] & mask) >> shift)))
        {
          if ((tmp_boards[i][j-1] == flag))
          {
            tmp_boards[i][j] = flag;
            ++counter;
            ++tmp_counter;
            continue;
          }
          else if (i > 0 && tmp_boards[i-1][j] == flag)
          {
            //look left
            tmp_boards[i][j] = flag;
            ++counter;
            ++tmp_counter;
            continue;
          }
          else if (i < 5 && tmp_boards[i+1][j] == flag)
          {
            //look right
            tmp_boards[i][j] = flag;
            ++counter;
            ++tmp_counter;
            continue;
          }
        }
      }
    }
    if (tmp_counter != 0)
    {
      for (i = 5; i < 6 ; --i)
      {
        //no need to look below as it has already been done in the previous loop
        if (tmp_boards[i][j] != flag)
        {
          if ((current_color == ((boards[i][j] & mask) >> shift)))
          {
            if (i > 0 && tmp_boards[i-1][j] == flag)
            {
              //look left
              tmp_boards[i][j] = flag;
              ++counter;
              continue;
            }
            else if (i < 5 && tmp_boards[i+1][j] == flag)
            {
              //look right
              tmp_boards[i][j] = flag;
              ++counter;
              continue;
            }
          }
        }
      }
    }
    tmp_counter = 0;
    ++j; //going below is getting higher j
  }
  
  //we started from 0, so at 3 we have 4 to erase
  if (counter >= 3)
  {
    //update the variable for point counting
    nb_puyos_destroyed[board_index] += (counter + 1); //how many puyos are destroyed on that hit
    // LSB p1, MSB p2, bit mask at 1 for each color present in the hit. bit 0 red, bit 1 blue, bit 2 green, 3 yellow
    mask_color_destroyed |= (1 << shift) << current_color;  
    nb_group[board_index] += (counter + 1) - 4;//if the group is over 4 puyos add the part over in this variable.

    //copy flag to boards
    for (i = 0; i < 6; ++i)
    {
      for (j = 12 ; j <= 12 ; --j)
      {
        if ( tmp_boards[i][j] == flag)
        {
          boards[i][j] |= flag;
          //tmp_boards[i][j] = 0;
          /*sprintf(str,"%d %d",i,j);
          vrambuf_put(NTADR_A(18,4+destruction),str,5);*/
          ++destruction;
        }
      }
    }
  }
  return destruction;
}

/*puyo visual destroying after check_board*/
byte destroy_board(byte board_index)
{
  byte i, j/*, current_color*/;
  byte counter = 0, tmp_line = 0;
  byte mask = 15, invmask = 240, flag = 8, shift = 0;
  byte destruction = 0;
  byte tmp_counter;
  register word addr;
  //char str[32];
  
  //memset(tmp_boards,0,sizeof(tmp_boards));
  if (board_index != 0)
  {
    shift = 4;
    mask <<= shift;
    invmask >>= shift;
    flag <<= shift; //the 8th bit unused by color will serve as flag to check colors.
    tmp_counter = step_p2_counter;
  }
  else
    tmp_counter = step_p1_counter;
  
  //step 0 we change the puyo to puyo_pop => e0
  if (tmp_counter == 0)
  {
    memset(ntbuf1, 0, sizeof(ntbuf1));
    memset(ntbuf2, 0, sizeof(ntbuf2));
    memset(attrbuf, 0, sizeof(attrbuf));

    set_metatile(0,0xe0); //0xe0 == puyo_pop
    for (i = 0; i < 6 ; i++)
    {
      for (j = 0; j < 13 ; j++)
      {
        if ((boards[i][j] & flag) > 0)
        {
          //(i+1)<<1 à l'air ok, y on y est pas encore
          //addr = NTADR_A((i+1)<<1, j *2 );//?????
          addr = NTADR_A(((i)*2)+2, j *2 );//?????
          vrambuf_put(addr|VRAMBUF_VERT, ntbuf1, 2);
          vrambuf_put(addr+1|VRAMBUF_VERT, ntbuf2, 2);
          /*addr = NTADR_A(i, (j)+2);
          vrambuf_put(addr|VRAMBUF_VERT, ntbuf1, 2);
          vrambuf_put(addr+1|VRAMBUF_VERT, ntbuf2, 2);*/
          //sujet traité, on zappe le flag
          boards[i][j] -= flag;
          //on change le board pour puyo_pop
          //PUYO_POP
          //(boards[x][y]&15) + (return_sprite_color(3) << 4);
          boards[i][j] = (boards[i][j] & invmask) + (PUYO_POP << shift);
          //we will reuse the flag for destruction
          boards[i][j] += flag;
          tmp_line=j;
          /*sprintf(str,"%d", j);
          vrambuf_put(NTADR_A(18,j*2),str,2);*/
        }
      }
    }
    
  }
  //step 1 we change the puyo_pop to nothing
  if (tmp_counter == 15)
  {
    memset(ntbuf1, 0, sizeof(ntbuf1));
    memset(ntbuf2, 0, sizeof(ntbuf2));
    memset(attrbuf, 0, sizeof(attrbuf));

    clear_metatile(0);
    for (i = 0; i < 6 ; i++)
    {
      for (j = 0; j < 13 ; j++)
      {
        if ((boards[i][j] & flag) > 0)
        {
          addr = NTADR_A(((i)*2)+2, j *2 );
          vrambuf_put(addr|VRAMBUF_VERT, ntbuf1, 2);
          vrambuf_put(addr+1|VRAMBUF_VERT, ntbuf2, 2);
          //sujet traité, on zappe le flag
          boards[i][j] -= flag;
          //on change le board pour EMPTY
          boards[i][j] = (boards[i][j] & invmask) + (EMPTY << shift);
        }
      }
    }
    //TODO à corriger pour P2 !
    step_p1 = POINT;
    step_p1_counter = 255;
  }
  
  step_p1_counter++;
  return 0;
}

/*puyo falling*/
byte fall_board(byte board_index)
{
  //TODO !
  //column_height doit être baissé (enfin montée, 0 est en haut) de 16 (+=16) à chaque fois qu'on descend un truc
  //on part d'en haut, de la première colonne, et on descend
  //step_p1_counter donne la colonne
  //on reconstruit d'abord la colonne sans trou dans boards[x][y]
  //ensuite on redessine toute la colonne dans le buffer.
  //si pas de changement on ne fait rien pour gagner en temps de calcul !
  byte j, j2;
  byte can_fall = 0, previous_empty = 0, puyo_found = 0;
  byte smask = 7, sinvmask = 112, mask = 15, invmask=240, flag = 8, shift = 0; /*on ne veut pas du flag pour les masques*/
  byte attr_x_shift = 1;
  byte fall = 0;
  byte tmp_counter;
  register word addr;
  //char str[32];
  
  //memset(tmp_boards,0,sizeof(tmp_boards));
  if (board_index != 0)
  {
    shift = 4;
    mask <<= shift;
    invmask >>= shift;
    flag <<= shift; //the 8th bit unused by color will serve as flag to check colors.
    attr_x_shift = 9;
    tmp_counter = step_p2_counter%6;
    /*if (tmp_counter > 5)
      return 0;*/
  }
  else
  { 
    tmp_counter = step_p1_counter%6;
    /*if (tmp_counter > 5)
      return 0;*/
  }
  
  for (j = 0 ; j < 13 ; j++)
  {
    if (can_fall != 1 && (boards[tmp_counter][j] & smask) != EMPTY)
    {
      puyo_found = j;// if no puyo are found then the column is empty=> need to reset height
      //as long as no puyo is found, there is nothing to get down
      can_fall = 1;
      if (j+1 < 13)
        j++;  
    }

    if (can_fall == 1 && (boards[tmp_counter][j] & smask) == EMPTY)
    {
      //this is where things get interesting, lets move everything down.
      //we start from j and get up to avoid overwriting values
      for (j2 = j ; j2 >= previous_empty && j2 < 255 ; j2--)
      {
        if (j2 == 0)
          boards[tmp_counter][j2] = (boards[tmp_counter][j2] & invmask) + (EMPTY << shift);
        else
          boards[tmp_counter][j2] = (boards[tmp_counter][j2] & invmask) + (boards[tmp_counter][j2-1] & mask);  
      }
      fall = 1;
      /*sprintf(str,"F %d", tmp_counter);
        vrambuf_put(NTADR_A(16,15+tmp_counter),str,8);*/

      //careful we wan't to only fall of 1 puyo height per cycle !
      //So we keep the position of the last element that has falled so top there
      previous_empty = j+1;
      can_fall = 0;
    }
  }
 
  if (fall == 1)
  {
    //If we got a fall we reset the counter, then 
    if (board_index != 0)
    {
      step_p2_counter = tmp_counter;
      //As it fall the height of the column must be lowered:
      column_height[tmp_counter+6] +=16;
    }
    else
    {
      step_p1_counter = tmp_counter;
      column_height[tmp_counter] +=16;
    }
    //redraw the column through buffer
    memset(ntbuf1, 0, sizeof(ntbuf1));
    memset(ntbuf2, 0, sizeof(ntbuf2));
    memset(attrbuf, 0, sizeof(attrbuf));
    //we start at 1 as we don't want to modify the ceiling
    for (j = 1; j < 13 ; j++)
    {
      
      switch (boards[tmp_counter][j] & mask)
      {
        case EMPTY:
          clear_metatile(j-1);
          attrbuf[j>>1] = return_tile_attribute_color(2,(tmp_counter+1)*2,j*2);
          break;
        case OJAMA:
          set_metatile(j-1,0xc5);
          attrbuf[j>>1] = return_tile_attribute_color(0,(tmp_counter+1)*2,j*2);
          break;
        case PUYO_RED:
          set_metatile(j-1,0xd8);
          attrbuf[j>>1] = return_tile_attribute_color(0,(tmp_counter+1)*2,j*2);
          break;
        case PUYO_BLUE:
          set_metatile(j-1,0xd8);
          attrbuf[j>>1] = return_tile_attribute_color(1,(tmp_counter+1)*2,j*2);
          break;
        case PUYO_GREEN:
          set_metatile(j-1,0xd8);
          attrbuf[j>>1] = return_tile_attribute_color(2,(tmp_counter+1)*2,j*2);
          break;
        case PUYO_YELLOW:
          set_metatile(j-1,0xd8);
          attrbuf[j>>1] = return_tile_attribute_color(3,(tmp_counter+1)*2,j*2);
          break;
      }
    } 
   
    //remplir les buffers nt et attr et ensuite faire le put !
    addr = NTADR_A(((tmp_counter)*2)+2, 2 );// le buffer contient toute la hauteur de notre tableau ! on commence en haut, donc 2
    vrambuf_put(addr|VRAMBUF_VERT, ntbuf1, 24);
    vrambuf_put(addr+1|VRAMBUF_VERT, ntbuf2, 24);
    put_attr_entries((nt2attraddr(addr)), 7);
    
  }
  else
  {
    //if something "fall" the counter is always reset to its 0 to 5 equivalent
    //so if nothing fall and we reach 11 (5th column) then a full "loop" as been done and we can continue
    if (puyo_found == 0)
    {  
      column_height[tmp_counter] = 190;
    }
    else
    {
      //if puyo_found kept the height of the first puyo found, with no fall
      //this is the heighest in the stack.
      column_height[tmp_counter] = ((puyo_found-1)*16) -2;
    }
    
    if (step_p1_counter == 11)
    {
      step_p1 = CHECK_ALL;
      step_p1_counter = 255;
    }
  }
  
  if (board_index != 0)
    step_p2_counter++;
  else
    step_p1_counter++;

  return board_index;
}

// Calcuate the point and update the score plus the ojama on top of opponent board
void manage_point(byte index_player)
{
  //based on this formula: https://www.bayoen.fr/wiki/Tableau_des_dommages
  //dommage hit = (10*nb_puyos_destroyed)*(hit_power + color_bonus + group_bonus)
  char str[6];
  byte tmp_mask = 0;
  unsigned long int tmp_score = 0;
  register word addr;
  
  //hit power
  tmp_score = (nb_hit[index_player] <= 3) ? ((nb_hit[index_player]-1) << 3) : (nb_hit[index_player]-3 << 5);
  
  //color_bonus
  //first get colors for current player
  tmp_mask = mask_color_destroyed & ((index_player == 0) ? 0xf : 0xf0);
 
  //then get nb of colors used from the mask by bitshift, substract 1 and multiply by 3
  tmp_score += (((tmp_mask & 1) + ((tmp_mask & 2) >> 1) + ((tmp_mask & 4) >> 2) + ((tmp_mask & 8) >> 3)) - 1) * 3;
 
  
  // group_bonus
  if ( nb_group[index_player] > 0 )
  {
    tmp_score += ( (nb_group[index_player] < 7) ? (nb_group[index_player] + 1) : 10 );
  }
  
  //you need to raise the score if bonus are null, to avoid multiply by 0
  if (tmp_score == 0)
    tmp_score = 1;
  
  //Now the disappearing puyos
  tmp_score = tmp_score * ((unsigned long) nb_puyos_destroyed[index_player] * 10);
  
  score[index_player] += tmp_score;
  
  //WIP add the opponent ojama removal from current player stack !
  if (index_player == 0)
  {
    ojamas[2] += tmp_score;
    if (ojamas[0] > 0)
    {  
      ojamas[0] = (ojamas[0] - tmp_score > ojamas[0] ) ? 0 : ojamas[0] - tmp_score ;
    }
  }
  else
  {
    ojamas[0] += tmp_score;
    if (ojamas[1] > 0)
    {  
      ojamas[1] = (ojamas[1] - tmp_score > ojamas[1] ) ? 0 : ojamas[1] - tmp_score ;
    }
  }
  
  //TODO print score
  //TODO update ojama on top of opponent //warikomi not handled yet
  sprintf(str,"%6lu", score[index_player]);
  addr = NTADR_A(6,27);
  vrambuf_put(addr,str,6);
  sprintf(str,"%6lu", ojamas[2]);
  addr = NTADR_A(20,1);
  vrambuf_put(addr,str,6);
  //reinit value for next compute
  nb_puyos_destroyed[index_player] = 0;
  mask_color_destroyed = mask_color_destroyed & 0xF0;
  nb_group[index_player] = 0;
}

void build_field()
{
  //register word addr;
  //byte i, x, y;
  byte x, y;
  //Filling up boards with EMPTY
  for (x = 0; x < 6; x++)
  {
    for (y = 0; y < 13; y++)
    {
      boards[x][y] = EMPTY + (EMPTY << 4);
      tmp_boards[x][y] = 0;
    }
  }
  
  //initialize attribute table to 0;
  memset(attribute_table,0,sizeof(attribute_table));
  for (x = 0; x < PLAYCOLUMNS; x+=2)
  {
    if (x == 0 || x == 30)
    {
      for (y = 0; y < PLAYROWS; y+=2)
      {
        vram_adr(NTADR_A(x,y));
        vram_put(0xc4);
        vram_put(0xc6);
        vram_adr(NTADR_A(x,y+1));
        vram_put(0xc5);
        vram_put(0xc7);
      }
    }
    else if (/* x == 8 ||x == 9 || x == 10 ||x == 11 || x == 12 || x == 13 ||*/ x == 14 || x == 15) //14 et 15
    {/* il faudra ici mettre les puyo à venir !*/
      for (y = 0; y < PLAYROWS; y+=2)
      {
        if ( y >= 4 && y <= 8 )
        {
          vram_adr(NTADR_A(x,y));
          vram_put(0xc8);
          vram_put(0xca);
          vram_adr(NTADR_A(x,y+1));
          vram_put(0xc9);
          vram_put(0xcb);
        }
        else
        {
          vram_adr(NTADR_A(x,y));
          vram_put(0xc4);
          vram_put(0xc6);
          vram_adr(NTADR_A(x,y+1));
          vram_put(0xc5);
          vram_put(0xc7);
        }
      }
    }
    else if (x == 16 || x == 17/* || x == 18 || x == 19 || x == 20*/) // 16 et 17
    {
      for (y = 0; y < PLAYROWS; y+=2)
      {
       if ( y >= 4 && y <= 8 )
        {
          vram_adr(NTADR_A(x,y));
          vram_put(0xc8);
          vram_put(0xca);
          vram_adr(NTADR_A(x,y+1));
          vram_put(0xc9);
          vram_put(0xcb);
        }
        else
        {
          vram_adr(NTADR_A(x,y));
          vram_put(0xc4);
          vram_put(0xc6);
          vram_adr(NTADR_A(x,y+1));
          vram_put(0xc5);
          vram_put(0xc7);
        }
      }
    }
    else
    {//le haut/ bas de l'air de jeu
      vram_adr(NTADR_A(x,0));
      vram_put(0xc4);
      vram_put(0xc6);
      vram_adr(NTADR_A(x,1));
      vram_put(0xc5);
      vram_put(0xc7);
      vram_adr(NTADR_A(x,PLAYROWS-4));
      vram_put(0xc4);
      vram_put(0xc6);
      vram_adr(NTADR_A(x,PLAYROWS-3));
      vram_put(0xc5);
      vram_put(0xc7);
      vram_adr(NTADR_A(x,PLAYROWS-2));
      vram_put(0xc4);
      vram_put(0xc6);
      vram_adr(NTADR_A(x,PLAYROWS-1));
      vram_put(0xc5);
      vram_put(0xc7);
    }
    
  }
  //colonne 0 et 31 sont pleines 
  //On peut pas mettre plus de 3 colonnes dans le buffer...
  /*
  vrambuf_clear();
  memset(ntbuf1, 0, sizeof(ntbuf1));
  memset(ntbuf2, 0, sizeof(ntbuf2));
  for (i = 0; i < PLAYROWS/2 - 1; i++)
  {
    set_metatile(i,0xc4);
  }
  addr = NTADR_A(0, 0);
  vrambuf_put(addr|VRAMBUF_VERT, ntbuf1, PLAYROWS);
  vrambuf_put((addr+1)|VRAMBUF_VERT, ntbuf2, PLAYROWS);
  //vrambuf_flush();
  addr = NTADR_A(2, 0);
  vrambuf_put(addr|VRAMBUF_VERT, ntbuf1, PLAYROWS);
  //vrambuf_put((addr+1)|VRAMBUF_VERT, ntbuf2, PLAYROWS);
  */
  
  // copy attribute table from PRG ROM to VRAM
  vram_write(attribute_table, sizeof(attribute_table));
}

// setup PPU and tables
void setup_graphics() {
  // clear sprites
  oam_clear();
   // clear sprites
  oam_hide_rest(0);
  // set palette colors
  pal_all(PALETTE);
   // clear vram buffer
  vrambuf_clear();
  set_vram_update(updbuf);
  seg_palette = rand8() & 3;
  seg_char = 0xe0;
}

void handle_controler_and_sprites(char i)
{
  pad = pad_poll(i);
  //update status of controller memory
  if (previous_pad[i]&PAD_LEFT && pad&PAD_LEFT)
    input_delay_PAD_LEFT[i]++;
  else
    input_delay_PAD_LEFT[i] = 0;
  if (previous_pad[i]&PAD_RIGHT && pad&PAD_RIGHT)
    input_delay_PAD_RIGHT[i]++;
  else
    input_delay_PAD_RIGHT[i] = 0;
  
  if (previous_pad[i]&PAD_A && pad&PAD_A)
    input_delay_PAD_A[i]++;
  else
    input_delay_PAD_A[i] = 0;
  if (previous_pad[i]&PAD_B && pad&PAD_B)
    input_delay_PAD_B[i]++;
  else
    input_delay_PAD_B[i] = 0;

  //you have to look at the leftmost or rightmost puyo
  //p1 puyo 0 & 1, p2 puyo 2 & 3
  if (actor_x[i*2] < actor_x[(i*2)+1])
  {
    //left/right
    if (pad&PAD_LEFT && actor_x[i*2] > (16+(i*128)))
    {
      //add a bit of delay before going again to left
      if (input_delay_PAD_LEFT[i] == 0 || input_delay_PAD_LEFT[i] > INPUT_DIRECTION_DELAY)
      {
        actor_x[i*2] -= 16;
        actor_x[(i*2)+1] -= 16;
      }
    }
    else if (pad&PAD_RIGHT && actor_x[(i*2)+1] < (96+(i*128)))
    {
      if (input_delay_PAD_RIGHT[i] == 0 || input_delay_PAD_RIGHT[i] > INPUT_DIRECTION_DELAY)
      {
        actor_x[i*2] += 16;
        actor_x[(i*2)+1] += 16;
      }
    }
    else
    { //doing nothing
      /*actor_x[i*2] = 0;
          actor_x[(i*2)+1] = 0;*/
    }
    //buttons, the puyo rotating is always the one at the top
    //so with index at 0 (0 p1, 2 p2)
    if (pad&PAD_B && input_delay_PAD_B[i] == 0)
    { 
      //here as puyo[0] < puyo[1] we are at the left, if we press
      //B the puyo will go under the 2nd puyo
      //the delay has to be at 0, because we don't want it to turn automatically
      //you have to press each time        
      actor_y[i*2] += 16;
      actor_x[i*2] += 16;
    }
    if (pad&PAD_A && input_delay_PAD_A[i] == 0)
    { 
      //here as puyo[0] < puyo[1] we are at the left, if we press
      //A the puyo will go over the 2nd puyo
      actor_y[i*2] -= 16;
      actor_x[i*2] += 16;
    }   
  }
  else
  {
    if (pad&PAD_LEFT && actor_x[(i*2)+1] > (16+i*128))
    {
      if (input_delay_PAD_LEFT[i] == 0 || input_delay_PAD_LEFT[i] > INPUT_DIRECTION_DELAY)
      {
        actor_x[i*2] -= 16;
        actor_x[(i*2)+1] -= 16;
      }
    }
    else if (pad&PAD_RIGHT && actor_x[i*2] < (96+i*128))
    {
      if (input_delay_PAD_RIGHT[i] == 0 || input_delay_PAD_RIGHT[i] > INPUT_DIRECTION_DELAY)
      {
        actor_x[i*2] += 16;
        actor_x[(i*2)+1] += 16;
      }
    }
    else
    {//doing nothing
      /*actor_dx[i*2] = 0;
          actor_dx[(i*2)+1] = 0;*/
    }

    if (actor_x[i*2] != actor_x[(i*2)+1])
    {
      //puyo[0] > puyo[1], it's on its right
      if (pad&PAD_B && input_delay_PAD_B[i] == 0)
      { 
        //here as puyo[0] > puyo[1] we are at the right, if we press
        //A the puyo will go over the 2nd puyo
        actor_y[i*2] -= 16;
        actor_x[i*2] -= 16;
      }
      if (pad&PAD_A && input_delay_PAD_A[i] == 0)
      { 
        //here as puyo[0] > puyo[1] we are at the right, if we press
        //A the puyo will go under the 2nd puyo
        actor_y[i*2] += 16;
        actor_x[i*2] -= 16;    
      }   
    }
    else
    {
      //same x for both puyo
      //B we go on the left, A we go on the right
      if (pad&PAD_B && input_delay_PAD_B[i] == 0)
      { 
        //we need to know if puyo[0] is above or below puyo[1]
        // the lowest value is higher on the screen !
        if (actor_y[i*2] < actor_y[(i*2)+1])
        {
          //going from up to left
          actor_x[i*2] -= 16;
          actor_y[i*2] += 16; 
        }
        else
        {  
          //going down to right
          actor_x[i*2] += 16;
          actor_y[i*2] -= 16; 
        }
      }
      if (pad&PAD_A && input_delay_PAD_A[i] == 0)
      { 
        if (actor_y[i*2] < actor_y[(i*2)+1])
        {
          // going from up to right
          actor_x[i*2] += 16;
          actor_y[i*2] += 16; 
        }
        else
        {
          //going from down to left
          actor_x[i*2] -= 16;
          actor_y[i*2] -= 16; 
        }   
      } 
    }
  }  
  previous_pad[i] = pad;
}

void main(void)
{
  char i;	// actor index
  char str[32];
  register word addr;
  byte should_destroy = 0;

  setup_graphics();
  // draw message  
  vram_adr(NTADR_A(2,3));
  vram_write("HELLO, WORLD!", 12);
  build_field();
  generate_rng();
  // initialize actors
  //P1
  actor_x[0] = 3*16;
  actor_y[0] = 0*16;
  actor_dx[0] = 0;
  actor_dy[0] = 1;
  actor_x[1] = 3*16;
  actor_y[1] = 1*16;
  actor_dx[1] = 0;
  actor_dy[1] = 1;
  p1_puyo_list_index = 0;
  //P2
  actor_x[2] = 11*16;
  actor_y[2] = 0*16;
  actor_dx[2] = 0;
  actor_dy[2] = 1;
  actor_x[3] = 11*16;
  actor_y[3] = 1*16;
  actor_dx[3] = 0;
  actor_dy[3] = 1;
  p2_puyo_list_index = 0;
    
  previous_pad[0] = 0;
  previous_pad[1] = 0;
  input_delay_PAD_A[0] = 0;
  input_delay_PAD_A[1] = 0;
  input_delay_PAD_B[0] = 0;
  input_delay_PAD_B[1] = 0;
  input_delay_PAD_LEFT[0] = 0;
  input_delay_PAD_LEFT[1] = 0;
  input_delay_PAD_RIGHT[0] = 0;
  input_delay_PAD_RIGHT[1] = 0;
  for (i = 0; i < 12 ; i++)
    column_height[i] = 190;

  step_p1 = PLAY;
  step_p2 = PLAY;
  step_p1_counter = 0;
  step_p2_counter = 0;
  
  //init score at 0
  memset(score,0,sizeof(score));
  
  // enable rendering
  ppu_on_all();
  //scroll(0,240);
  // infinite loop
  while(1) {
    //get input
    oam_id = 0;
    if (step_p1 == PLAY)
    {
      handle_controler_and_sprites(0);
      for (i = 0 ; i < 2 ; i++)
      {
        // puyoseq[0] == red, 1 blue, 2  green, 3 yellow, the good one is taken from
        // puyo_list       p1_puyo_list_index
        // (p1_puyo_list_index>>1) retourne le bon index puisqu'on a 4 paires par index
        // ensuite on décale sur le bon élément de l'index 
        // 2 bits pour chaque puyo=> on décale à droite (0<<0, 1<<2, 2<<4,3<<6)
        // et on fait & 3 pour ne garder que les 2 premiers bits    
        oam_id = oam_meta_spr(actor_x[i], actor_y[i], oam_id, puyoSeq[(puyo_list[(p1_puyo_list_index>>1)]>>((((p1_puyo_list_index%2)*2)+i)*2))&3]);

        if ( actor_dy[i] != 0)        
         actor_y[i] += (actor_dy[i] + ((previous_pad[0]&PAD_DOWN)? 2 : 0));

        //test relative to column_height
        if (actor_dy[i] != 0 && column_height[(actor_x[i]>>4) - 1] < actor_y[i])
        {
          actor_dy[i] = 0;
          actor_y[i] = column_height[(actor_x[i]>>4) - 1];
          column_height[(actor_x[i]>>4) - 1] -= 16;
        }
      }
    }
    else
    {
      //we need to move oam_id to not have an offset, should be a better way though...
      oam_id = oam_meta_spr(actor_x[0], actor_y[0], oam_id, puyoSeq[(puyo_list[(p1_puyo_list_index>>1)]>>((((p1_puyo_list_index%2)*2)+0)*2))&3]);
      oam_id = oam_meta_spr(actor_x[1], actor_y[1], oam_id, puyoSeq[(puyo_list[(p1_puyo_list_index>>1)]>>((((p1_puyo_list_index%2)*2)+1)*2))&3]);
    }
    
   if (step_p1 == FALL)
    {
      //execute before destroy to avoid doing destroy and fall consecutively
      fall_board(0);
    }
    
    if (step_p1 == POINT)
    {
      //execute before destroy to avoid doing destroy and fall consecutively
      nb_hit[0] += 1;
      manage_point(0);
      step_p1 = FALL;
    }

    if (step_p1 == DESTROY)
    {
      //need to avoid to start check in the same loop
      //need to see if we need to subdivise the work in several pass
      destroy_board(0);
    }
    
    if (step_p1 == CHECK && step_p1_counter == 0)
    {
      //reinit variables for counting point
      nb_puyos_destroyed[1] = 0; //how many puyos are destroyed on that hit      
      //we keep only p2 maskcolor
      mask_color_destroyed =  mask_color_destroyed & 0xF0; // LSB p1, MSB p2, bit mask at 1 for each color present in the hit. bit 0 red, bit 1 blue, bit 2 green, 3 yellow 
      nb_group[0] = 0;//if the group is over 4 puyos add the part over in this variable.
      
      should_destroy = (check_board(0, ((actor_x[0]>>3) - 2) >> 1, ((actor_y[0]>>3)+1)>>1) > 0);
      //if both puyo had the same color it's unless to perform the second check
      if ( (boards[((actor_x[1]>>3) - 2) >> 1][((actor_y[1]>>3)+1)>>1] & 8) != 8)
        should_destroy = (check_board(0, ((actor_x[1]>>3) - 2) >> 1, ((actor_y[1]>>3)+1)>>1) > 0) || should_destroy;
      
      if (should_destroy)
      {
        step_p1_counter = 0;
        step_p1 = DESTROY;
        //let's move sprites to not have them on screen when things explode
        actor_x[0] = 255;
        actor_y[0] = 255;
        actor_x[1] = 255;
        actor_y[1] = 255;
        should_destroy = 0;
      }
      else
      {
        actor_x[0] = 3*16;
        actor_y[0] = 0;
        actor_x[1] = 3*16;
        actor_y[1] = 16;
        actor_dy[0] = 1;
        actor_dy[1] = 1;
        p1_puyo_list_index++;
        step_p1 = PLAY;
        step_p1_counter = 0;
        // step_p1 = DESTROY;
        // Need to reset the boards flag to 0 after destroy!
      }
    } else if (step_p1 == CHECK && step_p1_counter != 0)
    {
      step_p1_counter = 0;
    }
    
    //after fall (and so destroy) we need to recheck all the board
    //Everything is fallen at that point, so we can go from bottom
    //to top and stop searching as soon empty is found
    if (step_p1 == CHECK_ALL)
    {
      if (step_p1_counter < 6)
      { //Start from the left column and go right, do bottom
        //1 column per step to keep some CPU (hopefully)
        i = 12;
        //must not be empty (5) and must not have the flag (8) set !
        while ( ((boards[step_p1_counter][i] & 7) != EMPTY) &&
                ((boards[step_p1_counter][i] & 8) != 8) &&
               i <= 12 )
        {
          should_destroy = (check_board(0, step_p1_counter, i) > 0) || should_destroy ;
          --i;
        }
        ++step_p1_counter;
      }
      else
      {
        //test is over, let's destroy if necessary
        if (should_destroy)
        {
          step_p1_counter = 0;
          step_p1 = DESTROY;
          should_destroy = 0;
        }
        else
        {
          actor_x[0] = 3*16;
          actor_y[0] = 0;
          actor_x[1] = 3*16;
          actor_y[1] = 16;
          actor_dy[0] = 1;
          actor_dy[1] = 1;
          p1_puyo_list_index++;
          step_p1 = PLAY;
          step_p1_counter = 0;
          nb_hit[0] = 0;// hit combo counter
        }
      }    
    }
   
 
    if (step_p2 == PLAY)
    {
      handle_controler_and_sprites(1);
      for (i = 2 ; i < 4 ; i++)
      {
        // puyoseq[0] == red, 1 blue, 2  green, 3 yellow, the good one is taken from
        // puyo_list       p1_puyo_list_index
        // (p1_puyo_list_index>>1) retourne le bon index puisqu'on a 4 paires par index
        // ensuite on décale sur le bon élément de l'index 
        // 2 bits pour chaque puyo=> on décale à droite (0<<0, 1<<2, 2<<4,3<<6)
        // et on fait & 3 pour ne garder que les 2 premiers bits
        oam_id = oam_meta_spr(actor_x[i], actor_y[i], oam_id, puyoSeq[(puyo_list[(p2_puyo_list_index>>1)]>>((((p2_puyo_list_index%2)*2)+(i-2))*2))&3]);
 
        actor_y[i] += (actor_dy[i] + ((previous_pad[1]&PAD_DOWN)? 2 : 0));

        //test relative to column_height
        /*if (actor_dy[i] != 0 && column_height[(actor_x[i]>>4) - 1] < actor_y[i])
        {
          actor_dy[i] = 0;
          actor_y[i] = column_height[(actor_x[i]>>4) - 1];
          column_height[(actor_x[i]>>4) - 1] -= 16;
        }*/
      }
    }

    //put_attr_entries(nt2attraddr(addr));

    if ( step_p1 == PLAY && actor_dy[0] == 0 && actor_dy[1] == 0)
    {
      //vrambuf_clear();
      memset(ntbuf1, 0, sizeof(ntbuf1));
      memset(ntbuf2, 0, sizeof(ntbuf2));
      memset(attrbuf, 0, sizeof(attrbuf));
      
      set_metatile(0,0xd8);
      //set_attr_entry((((actor_x[0]/8)+32) & 63)/2,0,return_sprite_color(0));
      //attrbuf should take the color for 4 tiles !
      attrbuf[0] = return_attribute_color(0, actor_x[0]>>3,(actor_y[0]>>3)+1, attribute_table);
      //HACK for unknown reason attribute_table is not correctly updated if function return_attribute_color is called twice
      //like here
      //attribute_table[(((actor_y[0]>>3)+1)<<1) + ((actor_x[0]>>3)>>2)] = attrbuf[0];
      set_metatile(1,0xd8);
      /*sprintf(str,"table:%d %d %d %d",attrbuf[0],actor_x[0]>>3,(actor_y[0]>>3)+1,(((actor_y[0]>>3)+1)<<1) + ((actor_x[0]>>3)>>2));
      addr = NTADR_A(1,26);
      vrambuf_put(addr,str,20);*/
      
      //set_attr_entry((((actor_x[1]/8)+32) & 63)/2,1,return_sprite_color(1));
      attrbuf[1] = return_attribute_color(1, actor_x[1]>>3, (actor_y[1]>>3)+1, attribute_table);/*return_sprite_color(1) + return_sprite_color(1)<<2 + return_sprite_color(1) << 4 + return_sprite_color(1) << 6*/;
      /*sprintf(str,"table:%d %d %d %d",attrbuf[1],actor_x[1]>>3,(actor_y[1]>>3)+1,(((actor_y[1]>>3)+1)<<1) + ((actor_x[1]>>3)>>2));
      addr = NTADR_A(1,27);
      vrambuf_put(addr,str,20);*/
      
      addr = NTADR_A((actor_x[0]>>3), (actor_y[0]>>3)+1);
      vrambuf_put(addr|VRAMBUF_VERT, ntbuf1, 2);
      vrambuf_put(addr+1|VRAMBUF_VERT, ntbuf2, 2);
      vrambuf_put(nt2attraddr(addr), &attrbuf[0], 1);

      addr = NTADR_A((actor_x[1]>>3), (actor_y[1]>>3)+1);
      vrambuf_put(addr|VRAMBUF_VERT, ntbuf1, 2);
      vrambuf_put(addr+1|VRAMBUF_VERT, ntbuf2, 2);
      vrambuf_put(nt2attraddr(addr), &attrbuf[1], 1);
      
      //updating the board, if things are done correctly attrbuf contains the color to be used
      //Still need to convert coordinates ! And not overwrite the value for the opponent board !
      update_boards(0);
     
      step_p1 = CHECK;
      //all commented below is now for another state
      /*
      if (check_board(0) > 0)
      {
        sprintf(str,"BOOM");
        addr = NTADR_A(20,15);
        vrambuf_put(addr,str,4);
      }
  
      actor_x[0] = 3*16;
      actor_y[0] = 0;
      actor_x[1] = 3*16;
      actor_y[1] = 16;
      actor_dy[0] = 1;
      actor_dy[1] = 1;
      p1_puyo_list_index++;*/
    }
    
    
    if (false && step_p2 == PLAY && actor_dy[2] == 0 && actor_dy[3] == 0)
    {/*
      set_metatile(2,0xd8);
      attrbuf[2] = return_attribute_color(2, actor_x[2]>>3,(actor_y[2]>>3)+1, attribute_table);

      set_metatile(3,0xd8);
      attrbuf[3] = return_attribute_color(3, actor_x[3]>>3, (actor_y[3]>>3)+1, attribute_table);

      addr = NTADR_A((actor_x[2]>>3), (actor_y[2]>>3)+1);
      vrambuf_put(addr|VRAMBUF_VERT, ntbuf1, 2);
      vrambuf_put(addr+1|VRAMBUF_VERT, ntbuf2, 2);
      vrambuf_put(nt2attraddr(addr), &attrbuf[2], 1);

      addr = NTADR_A((actor_x[3]>>3), (actor_y[3]>>3)+1);
      vrambuf_put(addr|VRAMBUF_VERT, ntbuf1, 2);
      vrambuf_put(addr+1|VRAMBUF_VERT, ntbuf2, 2);
      vrambuf_put(nt2attraddr(addr), &attrbuf[3], 1);
      
      //update_boards(2); //see the function to know why "2" in parameter
 
      actor_x[2] = 11*16;
      actor_y[2] = 0;
      actor_x[3] = 11*16;
      actor_y[3] = 16;
      actor_dy[2] = 1;
      actor_dy[3] = 1;
      p2_puyo_list_index++;*/
    }
    
    sprintf(str,"S1:%d, %d", step_p1, step_p1_counter);
    addr = NTADR_A(20,15);
    vrambuf_put(addr,str,10);
    
    if (oam_id!=0) 
      oam_hide_rest(oam_id);
    // ensure VRAM buffer is cleared
    ppu_wait_nmi();
    vrambuf_clear();
    //scroll(0,0);
  }
}
